### ISSUE TITLE
X.PagedList on MVC6

### ISSUE THREAD

**Issue by fedlerner** [kpi-ua/X.PagedList#11]
Does X.PagedList work on MVC6?
I have it working on an MVC5 project without any problems... But I recently started a new MVC6 project and I'm having trouble making PageList work. It fails to load the namespace, and the Helpers.. 
I haven't been able to make it work.

**Comment by ernado-x** [comment]
For the moment I not start implementing support for MVC 6.
But if you want do it - I will merge your implementation with current code base and include it to nuget package.

**Comment by chbach** [comment]
:+1: for MVC 6 support

**Comment by sky-code** [comment]
Hello, i implement mvc 6 compatibility and start pull request #18

**Comment by ernado-x** [comment]
@sky-code, thank you!

For now it is some problems with CI build. Can you help?

**Comment by sky-code** [comment]
Yep, i will try to help you solve this build error see #20

**Comment by eBerdnA** [comment]
Any news on this? #20 seems to be fixed.

Is the package for MVC6 already available on NuGET? I guess not because I couldn't find it.

**Comment by SavaMinic** [comment]
What's happening with this?
I included "X.PagedList.Mvc": "4.9.1.310" into project.json, and getting "X.PagedList.Mvc 4.9.1.310does not support framework DNXCore,Version=v5.0".

**Comment by Marren85** [comment]
Same problem for me, still doesn't work, why does dnx core cause so many problems?

**Comment by ernado-x** [comment]
Hey, all!
Thank you for your waiting. I had no time to make some updates :(
Now published beta version of MVC 6 compatible version at: https://www.nuget.org/packages/X.PagedList/5.0.0.3000-beta

Please view this package, and if you have any suggestions I will be glad improve this version.

Thank you all!

**Comment by himadrinath** [comment]
https://www.nuget.org/packages/X.PagedList/5.0.0.3000-beta

Error	CS0012	The type 'MvcHtmlString' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by jay5026** [comment]
I get the same error during compilation as @himadrinath

**Comment by VSG24** [comment]
Why is this MVC 6 version has dependency on System.Web??? This namespace doesn't exist in .net core.

**Comment by ernado-x** [comment]
@VSG24 please show, where you see this reference? I do not see it. 
![capture](https://cloud.githubusercontent.com/assets/3822922/14329098/872c931a-fc42-11e5-9da2-f5a384e6e9d8.PNG)

**Comment by jay5026** [comment]
![capture](https://cloud.githubusercontent.com/assets/16004049/14338179/a03ba242-fc29-11e5-9ebd-b2a055004b7e.PNG)
@ernado-x This might be what he is referring to (at least this is the problem I am having)

**Comment by jhrhilltop** [comment]
I have the same problem illustrated by the screenshot from @jay5026

**Comment by RealBrubru** [comment]
Same problem here, any fix??
Thanks

**Comment by ernado-x** [comment]
Unfortunately I cannot support ASP.NET Core (formerly ASP.NET MVC 6) version at this moment. So I deleted all code that related to .NET Core from master branch and cleaned up project.  ASP.NET Core  compatible version saved in  net-core branch. I think I will back to this code when .NET Core will be released. Sorry for inconvenience.
