### ISSUE TITLE
Fix CI build for MVC6 branch

### ISSUE THREAD

**Issue by ernado-x** [kpi-ua/X.PagedList#20]

**Comment by ernado-x** [comment]
@sky-code, may be  you can help to fix CI build for MVC6 branch?
Details at: https://travis-ci.org/ernado-x/X.PagedList/builds/95680484

**Comment by ernado-x** [comment]
https://travis-ci.org/ernado-x/X.PagedList/builds/95680509

**Comment by sky-code** [comment]
Hi, I do not have any experience with travis-ci, but from build log it is visible that build system not install packages for `X.PagedList.Mvc6` and `X.PagedList.Mvc6.Example` `xproj` projects

I think you need to update travis-ci configuration for new `xproj` projects

Please see this discusion on same problem https://github.com/travis-ci/travis-ci/issues/5164 with perhaps working solution

**Comment by sky-code** [comment]
All done, now travis build work fine
see #23 for details

**Comment by ernado-x** [comment]
Closed by 3b34ce797bc8c8d5aed54b3cfdd02de4efaf1eaf
