### ISSUE TITLE
Paging in MVC using PagedList

### ISSUE THREAD

**Issue by rpundlik** [kpi-ua/X.PagedList#25]
I have implemented Pagedlist.MVC and its working fine !

However, one issue I have which is as follows

In my application i have set the page size to 10 and I am retrieving the records same as page size(.i.e. 10 records) and not more than that.

However, while doing this Pagedlist package has disabled the next/prev button as my page size = number of records retrieved.

But, I have more records(say 150000) so in this case how can I keep the next/prev button enabled ?? 

I am not retrieving excess records due to performance issue. Hoever, I have the cound of total records.

So, how can I keep enable the next/prev button and also retrieve next 10 records ?

Regards,
Rohit

**Comment by ernado-x** [comment]
@rpundlik , as I understand, the page list control not know about total records count.
You can use StaticPagedList class in which you can set total count of records and  pass this information to control.

**Comment by rpundlik** [comment]
Thanks a lot ! That worked !
