### ISSUE TITLE
Calling method through ajax

### ISSUE THREAD

**Issue by rpundlik** [kpi-ua/X.PagedList#26]
Hello,

In PagedListPager we are calling method from URL.Action synchronously like follows,

    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Mailbox", new { page = page }), PagedListRenderOptions.Classic)

Can we call the same method through ajax  ?

Regards,
Rohit

**Comment by ernado-x** [comment]
Ye, I think you can implement separate view that can loaded by ajax.
