### ISSUE TITLE
Next Prev between the records

### ISSUE THREAD

**Issue by rpundlik** [kpi-ua/X.PagedList#27]
Hello,

How can I navigate(next-prev) between the records and NOT into the page ?

Regards,
Rohit

**Comment by ernado-x** [comment]
Sorry. Do not understand your question.

**Comment by rpundlik** [comment]
Sorry for giving detailed explaination.
Lets say I have 10 records and I clicked on first record(Record # 1) for its detailed view, then I want to move to next record((Record # 2) and vice versa.  Basically I want to navigate between the available records.

So can we achieve this using Pagedlist ?

Regards,
Rohit
