### ISSUE TITLE
Convert PagedList to List

### ISSUE THREAD

**Issue by mdmoura** [kpi-ua/X.PagedList#28]
Hello,
	
On an ASP.NET MVC project and I have the following:

    PagedList<TestModel> models = _service.Get(2, 20);

The service always return a PagedList but I need to create a List with only the items in PagedList and without the paging metadata.

I tried the following:
    IList<TestModel>)models.GetEnumerator()

No success. Is it possible to convert a PagedList to List?

Thank You,
Miguel

**Comment by dphoebus** [comment]
I realize this is a little old but PagedList<T> implements IEnumerable<T>.  If you want a List<T> from a PagedList<T> simply call ToList().

```csharp
var data = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
var pagedList = data.ToPagedList(1, 5);
var list = pageList.ToList();
```

If you have already figured this out just ignore me! :+1:

Dan

**Comment by ernado-x** [comment]
@dphoebus  is right. PagedList supports ToList() method.

**Comment by MillieNakiganda** [comment]
PagedList doesn't support ToList()...

you can convert from PagedList to IEnumerable using this:
IPagedList as IEnumerable<ModelClass>
