### ISSUE TITLE
[Question] Call js function instead of redirect to url

### ISSUE THREAD

**Issue by julianonunes** [kpi-ua/X.PagedList#29]
Is it possible to add a js function call to the link's onclick attribute instead of setting the href attribute? My grid has filters that use POST method and I have to keep them when navigating between pages.

**Comment by Eonasdan** [comment]
hey @julianonunes I had a similar issue and I wanted to share my workaround.

I have a hidden field in my form called `PageNumber`:

```
$('.pagination-container a').click(function (e) {
	e.preventDefault();
	$('#PageNumber').val(this.href.replace(this.origin, '').replace('BASEURL?page=', ''));
	$('#FORM').submit();
});
```

What this code does is intercepts clicking on the pager, replaces the href origin (`http://foo.com`) and `BASEURL` which you will need to change so `/Page/Search`. That should give the actual page number. With the page number in hand, I've stuffed that into my textbox and then submit the `FORM`.

Hope that help!

**Comment by ernado-x** [comment]
Hope that @Eonasdan suggestion help you. Please reopen issue if problem not solved.
