### ISSUE TITLE
Parameterize Skip and Take for Entity Framework

### ISSUE THREAD

**Issue by philip-reed** [kpi-ua/X.PagedList#30]
PagedList currently passes 'int' to the .Skip() & .Take() methods of Entity Framework.
This means that the SQL generated does not parameterise these variables and prevents databases from caching the execution plan for the SQL.

Instead, if a lambda was passed to the .Skip() & .Take() methods, Entity Framework (EF6) would instead generate parameters for these variables and allow databases to better cache the execution plan.

See here for more information:
http://anthonychu.ca/post/entity-framework-parameterize-skip-take-queries-sql/

**Comment by ernado-x** [comment]
Now X.PagedList is PCL assembly and cannot support lambdas as method arguments for Take and Skip methods.
But I think this functionality may be implemented over extension method in specified project.
