### ISSUE TITLE
Issues with Nuget package for X.PagedList.Mvc6

### ISSUE THREAD

**Issue by ephremshiferaw** [kpi-ua/X.PagedList#34]
there seems to be some binding mismatch on the nuget package for X.PagedList.Mvc6, please see error 

'X.PagedList.Mvc6' with identity 'X.PagedList.Mvc6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'X.PagedList, Version=5.0.5.1920, Culture=neutral, PublicKeyToken=abbb863e9397c5e1' which has a higher version than referenced assembly 'X.PagedList' with identity 'X.PagedList, Version=5.0.5.1782, Culture=neutral, PublicKeyToken=abbb863e9397c5e1'

**Comment by simon25608** [comment]
I have the same error :(

**Comment by peterorjeff** [comment]
same here.

any ETA on a fix for this?

**Comment by ernado-x** [comment]
Unfortunately I cannot support ASP.NET Core (formerly ASP.NET MVC 6) version at this moment. So I deleted all code that related to .NET Core from master branch and cleaned up project.  ASP.NET Core  compatible version saved in  net-core branch. I think I will back to this code when .NET Core will be released. Sorry for inconvenience.

**Comment by giocaputo** [comment]
We can reopen it?!
