### ISSUE TITLE
Convert the pager HtmlHelper to TagHelper

### ISSUE THREAD

**Issue by musabsudan** [kpi-ua/X.PagedList#35]
I think it is the time to convert the pager HtmlHelper to TagHelper, clean up the code and remove the unnecessary if's.

**Comment by ernado-x** [comment]
Sorry, but .NET Core support is [at hold](https://github.com/kpi-ua/X.PagedList#about-net-core-support) for now.

**Comment by Olbrasoft** [comment]
https://github.com/Olbrasoft/Paging.X.PagedList.AspNetCore.Mvc
