### ISSUE TITLE
.ToListAsync issue with Threading 

### ISSUE THREAD

**Issue by poseidonredsea** [kpi-ua/X.PagedList#36]
Good Day:

I have model when I convert it to pagedlistAsync it won't work and shows error on the page as this:

**Could not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**

but when I do it like this : 

           var postsList = await model.ToListAsync();      
            var postsByPage = postsList.ToPagedList(pageNo ?? 1, 10);
            ViewData["featuredHome"] = featuredPost as BlogListView;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_BlogPostsList", postsByPage);
            }
               
                return View(postsByPage);

it works only when I convert the model to listAsync then after I convert to PagedList. 

I would like to know if that's issue or There is a mistake in my assemblies 

Thanks

**Comment by ernado-x** [comment]
I created new ASP.NET MVC project and had tried reproduce your problem, but I had no success – your code works fine in my case.
