### ISSUE TITLE
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0

### ISSUE THREAD

**Issue by tomaskikutis** [kpi-ua/X.PagedList#44]
It works well locally, but breaks in production. If I copy `System.Runtime.dll` from local bin to production bin, production also starts working. I tried to copy `System.Runtime.dll` to custom folder and add reference to it, but got an error about duplicate references.
Ended up using original [PagedList](https://github.com/troygoode/PagedList). Everything stared working after changing using declaration(to PagedList instead of X.PagedList) and no other changed had to be made.

I'm using it from razor view / MVC5 application.

**Comment by ernado-x** [comment]
This is known problem: http://www.lyalin.com/2014/04/25/the-type-system-object-is-defined-in-an-assembly-that-is-not-reference-mvc-pcl-issue
This applies to whole web app, not single library.

**Comment by tomaskikutis** [comment]
Do you know why this error doesn't occur in original PagedList ? Isn't there a way to fix this in library level ?

**Comment by mvpkenlin** [comment]
I have the similar error, 
https://github.com/kpi-ua/X.PagedList/issues/59

I also ended up using the original PagedList and the error has gone. Why close this issue? There must be something wrong in this project from original PagedList
